### ISSUE TITLE
Upgrade to Swift 5.5?

### ISSUE THREAD

**Issue by galeo** [roeybiran/dash-docset-swift-5.3-language-guide#1]
Swift 5.5 is released, would you like to upgrade this docset to the latest version of the swift language guide? Thanks.

**Comment by roeybiran** [comment]
Yes, I’m working on it along with some major improvements to the generator code. Stay tuned!

**Comment by roeybiran** [comment]
Done!  [Kapeli/Dash-User-Contributions/pull/3454](https://github.com/Kapeli/Dash-User-Contributions/pull/3454)
